### ISSUE TITLE
Compile instructions

### ISSUE THREAD

**Issue by fakusb** [uds-psl/H10#2]
the readme instructs to cd into H10 and make there, but there is no makefile in the H10 folder

**Comment by DmxLarchey** [comment]
Well after git clone, there should be a `H10` and a also `H10/H10` dir. The `cd H10` is for the first one only.

Maybe the `README` file should be more specific about that point ?

**Comment by fakusb** [comment]
Oh, yeah...
I just thought there was a separate makefile in H10 to only compile the relevant files.
